export const COUNTRY_NAMES: Record<string, string> = {
  US: 'United States',
  GB: 'United Kingdom',
  DE: 'Germany',
  FR: 'France',
  CA: 'Canada',
  AU: 'Australia',
  IN: 'India',
  BR: 'Brazil',
  JP: 'Japan',
  IT: 'Italy',
  ES: 'Spain',
  NL: 'Netherlands',
  SE: 'Sweden',
  CH: 'Switzerland',
  MX: 'Mexico',
  KR: 'South Korea',
  RU: 'Russia',
  PL: 'Poland',
  BE: 'Belgium',
  AT: 'Austria',
  NO: 'Norway',
  DK: 'Denmark',
  FI: 'Finland',
  PT: 'Portugal',
  IE: 'Ireland',
  NZ: 'New Zealand',
  SG: 'Singapore',
  HK: 'Hong Kong',
  TW: 'Taiwan',
  IL: 'Israel',
  ZA: 'South Africa',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colombia',
  TH: 'Thailand',
  PH: 'Philippines',
  MY: 'Malaysia',
  ID: 'Indonesia',
  VN: 'Vietnam',
  TR: 'Turkey',
  CZ: 'Czech Republic',
  RO: 'Romania',
  HU: 'Hungary',
  GR: 'Greece',
  UA: 'Ukraine',
  EG: 'Egypt',
  NG: 'Nigeria',
  KE: 'Kenya',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  AE: 'United Arab Emirates',
  SA: 'Saudi Arabia',
}

export const countryName = (code: string): string => COUNTRY_NAMES[code] || code
