catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - packages/*

catalog:
  '@modelcontextprotocol/sdk': ^1.26.0
  '@types/js-yaml': ^4.0.9
  '@types/node': ^25.0.9
  js-yaml: ^4.1.1
  tinyexec: ^1.0.2
  vitest-package-exports: ^1.1.2
  zod: ^4.3.5

catalogs:
  deps:
    '@clack/prompts': ^0.11.0
    '@googleapis/indexing': ^6.0.1
    '@googleapis/searchconsole': ^6.0.1
    citty: ^0.1.6
    consola: ^3.4.2
    dayjs: ^1.11.19
    defu: ^6.1.4
    google-auth-library: ^10.5.0
    ofetch: ^1.5.1
    open: ^11.0.0
    ufo: ^1.6.3
  dev-build:
    bumpp: ^10.4.0
    obuild: ^0.4.14
    typescript: ^5.9.3
  dev-lint:
    '@antfu/eslint-config': ^7.0.1
    eslint: ^9.39.2
  dev-test:
    dotenv: ^17.2.3
    vitest: ^4.0.17

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - gtoken
  - unrs-resolver
  - vue-demi
