// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/analysis-sources': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analysis-sources.get').default>>>>
    }
    '/api/analysis/:analyzer': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analysis/[analyzer].get').default>>>>
    }
    '/api/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manifest.get').default>>>>
    }
    '/api/r2-data/**:path': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/r2-data/[...path].get').default>>>>
    }
    '/api/sign-url': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sign-url.get').default>>>>
    }
    '/api/sign-urls': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sign-urls.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@4.4.2_@babel+core@7.29.0_aws4fetch@1.0.20_db0@0.3.4_drizzle-orm@0.45_968fc240f6d2bff0f3c94df268e7dd0b/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}