export const partnerRoutes = {
  partner: {
    users: {
      byId: (userId: string) => `/partner/users/${encodeURIComponent(userId)}`,
      lifecycle: (userId: string) => `/partner/users/${encodeURIComponent(userId)}/lifecycle`,
      siteTeam: (userId: string, siteId: string) => `/partner/users/${encodeURIComponent(userId)}/sites/${encodeURIComponent(siteId)}`,
    },
    sites: {
      register: '/partner/sites/register',
      bulkRegister: '/partner/sites/bulk-register',
    },
  },
  users: {
    register: '/users/register',
    tokens: (userId: string) => `/users/${encodeURIComponent(userId)}/tokens`,
    status: (userId: string) => `/users/${encodeURIComponent(userId)}/status`,
    lifecycle: (userId: string) => `/users/${encodeURIComponent(userId)}/lifecycle`,
    sites: (userId: string) => `/users/${encodeURIComponent(userId)}/sites`,
    availableSites: (userId: string) => `/users/${encodeURIComponent(userId)}/available-sites`,
    siteTeam: (userId: string, siteId: string) => `/partner/users/${encodeURIComponent(userId)}/sites/${encodeURIComponent(siteId)}`,
  },
  sites: {
    register: '/sites/register',
    bulkRegister: '/sites/bulk-register',
    byId: (siteId: string) => `/sites/${encodeURIComponent(siteId)}`,
    analysisSources: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/analysis-sources`,
    syncStatus: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/sync-status`,
    data: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/data`,
    dataDetail: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/data/detail`,
    analysis: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/analysis`,
    sitemaps: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/sitemaps`,
    sitemapChanges: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/sitemaps/changes`,
    indexing: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/indexing`,
    indexingUrls: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/indexing/urls`,
    indexingDiagnostics: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/indexing/diagnostics`,
    recoverPermission: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/recover-permission`,
    canonicalMismatches: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/canonical-mismatches`,
    topAssociation: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/data/top-association`,
    keywordSparklines: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/data/keyword-sparklines`,
    queryTrend: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/data/query-trend`,
    contentVelocity: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/content-velocity`,
    ctrCurve: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/ctr-curve`,
    darkTraffic: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/dark-traffic`,
    deviceGap: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/device-gap`,
    indexPercent: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/index-percent`,
    keywordBreadth: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/keyword-breadth`,
    positionDistribution: (siteId: string) => `/sites/${encodeURIComponent(siteId)}/position-distribution`,
  },
  settings: {
    user: '/user/settings',
  },
  teams: {
    create: '/partner/teams',
    byId: (teamId: string) => `/partner/teams/${encodeURIComponent(teamId)}`,
    members: (teamId: string) => `/partner/teams/${encodeURIComponent(teamId)}/members`,
    member: (teamId: string, userId: string) => `/partner/teams/${encodeURIComponent(teamId)}/members/${encodeURIComponent(userId)}`,
  },
  realtime: {
    partner: '/ws/partner',
    user: '/ws/user',
  },
} as const

export const analyticsRoutes = {
  whoami: '/api/__gsc/whoami',
  sites: '/api/__gsc/sites',
  site: {
    sourceInfo: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/source-info`,
    analysisSources: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/analysis-sources`,
    analyze: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/analyze`,
    rows: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/rows`,
    rollup: (siteId: string, rollupId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/rollup/${encodeURIComponent(rollupId)}`,
    backfill: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/backfill`,
    sitemaps: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/sitemaps`,
    sitemapHistory: (siteId: string, hash: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/sitemaps/${encodeURIComponent(hash)}`,
    sitemapChanges: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/sitemaps/changes`,
    inspections: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/inspections`,
    inspectionHistory: (siteId: string, hash: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/inspections/${encodeURIComponent(hash)}`,
    indexingUrls: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/indexing/urls`,
    indexingDiagnostics: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/indexing/diagnostics`,
    countries: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/countries`,
    searchAppearance: (siteId: string) => `/api/__gsc/sites/${encodeURIComponent(siteId)}/search-appearance`,
  },
} as const
